### ISSUE TITLE
用不了啦，列表刷不出来，全是空白。

### ISSUE THREAD

**Issue by xiaoOops** [marud1024/1024#5]
更新的最新版，首页、最近更新、当前最热……所有tab的列表都刷新不出来，已经排除是网络或者梯子问题。

**Comment by marud1024** [comment]
我正常使用的

**Comment by marud1024** [comment]
设置里面改下地址 改成官方地址试试

**Comment by falltoearth** [comment]
> 我正常使用的

借个楼，作者下载功能正常吗？我的下载下来都是只有2kb

**Comment by marud1024** [comment]
下载不行了 视频是m3u8格式的了 下不了了

**Comment by xiaoOops** [comment]
改了地址，可以用了。就是视频缓冲很慢，好像不是网络原因。
